# Generated by Django 3.0.3 on 2020-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_admin', '0002_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
